Repository AY2324S2-CS2113-T13-3/tp, pull requests merged in 2024-04, with the labels that each got.

#260 Update UG
  docs/UserGuide.md
  src/main/java/classify/commands/ListStudentsCommand.java
  src/test/java/classify/commands/AddStudentTest.java
  src/test/java/classify/commands/ListStudentsCommandTest.java
  src/test/java/classify/commands/StudentSorterTest.java
  src/test/java/classify/student/StudentAttributesTest.java
Labels: documentation

#261 Update the User Guide
  docs/UserGuide.md
  src/main/java/classify/ui/UI.java
  src/test/java/classify/user/InputParsingTest.java
Labels: documentation

#266 Update functionality for the process command
  src/main/java/classify/textfilecode/TextFileParser.java
  src/main/java/classify/user/InputParsing.java
Labels: enhancement

#267 Bug fixing
  src/main/java/classify/textfilecode/TextFileParser.java
  src/main/java/classify/user/InputParsing.java
Labels: bug

#271 Update README file to match our product
  docs/README.md
  docs/team/tayponghee.md
  src/main/java/classify/classgroup/Class.java
  src/main/java/classify/classgroup/ClassList.java
  src/main/java/classify/commands/DeleteCommands.java
  src/main/java/classify/ui/UI.java
  src/test/java/classify/classgroup/ClassListTest.java
  src/test/java/classify/classgroup/ClassTest.java
  src/test/java/classify/commands/DeleteCommandsTest.java
  src/test/java/classify/student/StudentAttributesTest.java
  src/test/java/classify/user/InputParsingTest.java
Labels: documentation, enhancement

#272 Add classes attended for each subject
  docs/UserGuide.md
  src/main/java/classify/commands/ListStudentsCommand.java
  src/test/java/classify/commands/ListStudentsCommandTest.java
Labels: documentation, enhancement

#293 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#298 Update UG, DG, Test Cases
  docs/DeveloperGuide.md
  docs/SampleFile.txt
  docs/Text File Format Picture.jpg
  docs/UserGuide.md
  src/main/java/classify/textfilecode/TextFileParser.java
  src/test/java/classify/textfilecode/TextFileParserTest.java
  src/test/java/classify/textfilecode/TextFileReaderTest.java
Labels: documentation

#299 Update DG, PPP, About Us. Clean Code
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/Parth Image.JPG
  docs/team/parthgandhinus.md
  src/main/java/classify/commands/AddStudent.java
  src/main/java/classify/commands/ListStudentsCommand.java
  src/main/java/classify/data/DataReader.java
  src/main/java/classify/textfilecode/TextFileParser.java
  src/main/java/classify/textfilecode/TextFileReader.java
  src/main/java/classify/user/InputParsing.java
  src/test/java/classify/data/DataReaderTest.java
  src/test/java/classify/textfilecode/TextFileParserTest.java
Labels: documentation, enhancement

#300 Update DG, Bug Fix Process Functionality
  docs/DeveloperGuide.md
  src/main/java/classify/textfilecode/TextFileHandler.java
  src/main/java/classify/textfilecode/TextFileReader.java
Labels: bug, documentation, enhancement

#307 Update Docu
  docs/UserGuide.md
  docs/team/parthgandhinus.md
Labels: documentation

#308 Update UG
  docs/UserGuide.md
Labels: documentation

#315 UG Finale
  docs/UserGuide.md
Labels: documentation

#316 Update PPP
  docs/team/parthgandhinus.md
Labels: documentation

#318 Update DG
  docs/DeveloperGuide.md
Labels: documentation
